@if(auth()->user()?->isSupplier())
    <x-layouts.dashboard>
        @include('booking.manage-content')
    </x-layouts.dashboard>
@else
    <x-app-layout>
        @include('booking.manage-content')
    </x-app-layout>
@endif
